### ISSUE TITLE
Unable to download/read data query - Likely web host (UserProjectAccountProblemUser/Datahub)

### ISSUE THREAD

**Issue by ericoulster** [database-of-embassies/database-of-embassies#39] opened 2020-05-05 22:48 UTC
This seems like an interesting dataset, but I seem unable to download or view the results of it.

When clicking on the data source, I am given the following error:
'UserProjectAccountProblemUser project billing account not in good standing.The billing account for the owning project is disabled in state absent'.

**Comment by nicolas-raoul** [comment] 2020-05-06 06:18
Thanks for your feedback!
Unfortunately I was not able to reproduce the problem.
Could you please post a screenshot, including the browser URL bar?
Thanks! :-)

**Comment by ericoulster** [comment] 2020-05-06 12:28
I am still getting an error with pulling the dataset, though this is the one I am contending with trying to pull the data using the query.

I originally though this may have to do with my browser add-ons (i.e. JS blockers), but on my add-on less google chrome I am encountering the same error 
![Sparql-query error](https://user-images.githubusercontent.com/40222141/81176635-682cd100-8f73-11ea-9d43-15aefebf6fb8.png)

It dawned on me the original error I encountered (the one with the UserProjectAccountProblemUser) may have come from the link that led me to this repo (from datahub)

**Comment by nicolas-raoul** [comment] 2020-05-07 02:38
Datahub! I have not been there for years but I should check.
Would you mind creating a new issue for the timeout error? Thanks!

**Comment by ericoulster** [comment] 2020-05-07 04:40
Sure thing

**Comment by nicolas-raoul** [comment] 2020-10-22 02:32
Datahub seems to be totally broken.
It does not allow me to log in with my username/password, and both its Google and GitHub authentications are broken in different ways. Search is broken too.

The only official way to download the dataset currently is via HTTP download on this GitHub project, which I think is easy enough, so let's close this for now :-)

**Closed as completed by nicolas-raoul** 2020-10-22 02:32 UTC
Labels: bug
